### ISSUE TITLE
Doesn't Seem To Work

### ISSUE THREAD

**Issue by amadeus** [d11wtq/ctrlp_bdelete.vim#1]
For some reason, this doesn't seem to work. I am using NeoBundle, which is basically the same as Vundle/Pathogen.

On load I get:
![image](https://dl.dropboxusercontent.com/s/wt9vkxcxxzj8cyv/alert.js_20140508_182426_20140508_182428.png)

Trying to figure out why the autoload might not be getting sourced...

**Comment by amadeus** [comment]
Figured it out.

The command to run it in the readme is incorrect, it needs to be

```
call ctrlp_bdelete#init()
```

**Comment by amadeus** [comment]
P.S. Thanks for making this, it looks like it works well!

**Comment by d11wtq** [comment]
Oh, thanks for the heads up. Fixed the README.
