### ISSUE TITLE
Can't call init() several times

### ISSUE THREAD

**Issue by wdesmet** [d11wtq/ctrlp_bdelete.vim#3]
Calling init() always seems to store the previous handler and then call it. If you call it twice, this introduces some sort of recursive loop causing the stack to overflow. Since the default advice is to call it in the vimrc, this does happen to me from time to time when I resource my vimrc. Either the plugin should recognize its own handler or detect that it's been loaded before and do nothing in that case.

**Comment by d11wtq** [comment]
Oh yeah, that should be easy to fix with a guard clause! Thanks for the heads-up :)

**Comment by d11wtq** [comment]
Fixed in 7f354de.
