### ISSUE TITLE
fails to work in gvim/vim-X11

### ISSUE THREAD

**Issue by apegushin** [d11wtq/ctrlp_bdelete.vim#8]
I tried changing C-@ mapping to something else (both num row and regular keys) in the plugin file thinking that C-@ is simply masked in gui version, but that did not work. None of the ones I tried succeded in closing a buffer. At the same time C-Z marks them just fine. And ctrlp_bdelete worked perfectly in terminal vim. Thank you for looking into this.

**Comment by dgronskij** [comment]
The same behaviour, terminal VIM works this out perfectly while gVIM shows "Type  :quit<Enter>  to exit Vim " and does nothing.

**Comment by apegushin** [comment]
@dgronskij yes, this is exactly what gvim shows for me too, when I hit ctrl+@.

**Comment by d11wtq** [comment]
This plugin is actually obsolete now, if you use the latest version of ctrlp.vim from https://github.com/ctrlpvim/ctrlp.vim, which includes some better buffer explorer functionality. F7 is mapped to delete marked buffers, like this plugin does.

**Comment by apegushin** [comment]
@d11wtq thank you!

**Comment by dgronskij** [comment]
Just realized that I was using kien's (depcracated) version of CtrlP. @d11wtq , thank you!

**Comment by bobo2007** [comment]
@dgronskij  me too！ 😟
